### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by ewallah** [Limekiller/moodle-block_openai_chat#11]
Invalid get_string() identifier: 'openai_chat:addinstance' or component 'block_openai_chat'. 
Perhaps you are missing $string['openai_chat:addinstance'] = ''; in blocks/openai_chat/lang/en/block_openai_chat.php?
        line 356 of /lib/classes/string_manager_standard.php: call to debugging()

Invalid get_string() identifier: 'openai_chat:myaddinstance' or component 'block_openai_chat'.
Perhaps you are missing $string['openai_chat:myaddinstance'] = ''; in /blocks/openai_chat/lang/en/block_openai_chat.php?
        line 356 of /lib/classes/string_manager_standard.php: call to debugging()

**Comment by Limekiller** [comment]
Thanks for the report. Fixed in f970ba6 (1.5.0)
