### ISSUE TITLE
what's the type of the error and how can i fix it?

### ISSUE THREAD

**Issue by somiceast** [Limekiller/moodle-block_openai_chat#15]
Hi,
Thanks for your fancy work! 

Here is my server status: 3.10.0 Moodle, CentOS 7.

I just registered the openAI account. After installed your plugin on my moodle website and input the API key, I found the openAI block did not respond with this error (graph below). The openAI API list shows the APIkey has not been used. My server
In my area, openAI is not avalible and I need VPN to access website. Is that matters?What error is it and how can I fix it? 
Thanks for your attention.

Here is the error screenshot:
<img width="352" alt="Screenshot 2023-03-21 at 19 26 56" src="https://user-images.githubusercontent.com/8175751/226592993-9a8474e6-47c7-459c-9efa-078db04406df.png">

**Comment by Limekiller** [comment]
Hi somiceast, this error indicates that the JavaScript wasn't able to complete a fetch call to the completion API endpoint. You might be able to see what happened by going to the network tab of the inspector and seeing the response to the completion.php request.

I tried installing the plugin on a 3.10 site just now and wasn't able to reproduce this, so please let me know what you find.

**Comment by somiceast** [comment]
Thank u for helping!
I found completion.php in the network tab of the inspector respond this error:

> "Failed to connect to api.openai.com port 443: Connection timed out".

After googleed the error code I guess it because of the region (openai is not avaliable in my area) or vpn, i used clashX global proxy on my computer still not work.
what should I do next?

post:
POST /moodle/blocks/openai_chat/api/completion.php HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Connection: keep-alive
Content-Length: 53
Content-Type: text/plain;charset=UTF-8
Cookie: MoodleSession=0rk7d6vjf0vp005929p7a3oe16; MOODLEID1_=%25FA%252B%2582%2515; _km_id=q9qNcZNgTihyaum8T2NVWq5XDaxNoP6p; _km_user_name=Witty Seahorse; _km_lead_collection=false
DNT: 1
Host: moodlenlm.xyz
Origin: https://moodlenlm.xyz
Referer: https://moodlenlm.xyz/moodle/my/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

respond:
HTTP/1.1 200 OK
Date: Sat, 01 Apr 2023 12:03:52 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/7.3.24
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Length: 66
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8

**Comment by Limekiller** [comment]
Unfortunately it sounds like the issue is that the GPT API is blocked in your region, which I can't do anything about. The only thing I can think of suggesting is to use a VPN; if that doesn't work, there may not be anything you can do. Sorry.
