### ISSUE TITLE
Render HTML in the chat messages, esp. for ChatGPT's code examples.

### ISSUE THREAD

**Issue by fishfree** [Limekiller/moodle-block_openai_chat#16]
As mentioned in the title. Thanks!

**Comment by Limekiller** [comment]
Hi, could you expand on what you're looking for here? Right now, the response from GPT is inserted as-is into the HTML, meaning that tags are already interpreted and rendered. I'm not super interested in providing a lot of formatting features here along the lines of the ChatGPT front end, as that balloons the complexity of the plugin -- but if you're looking for something relatively simple that provides a significant improvement I'll definitely consider it.

**Comment by michael-milette** [comment]
Hi @Limekiller,

The OpenAI API returns completion messages in markdown format. What is needed is to simply pass the output through Moodle's format_text() function.

Please take a look at the following PR: #27 for a solution.

Hope you find this helpful.

Best regards,

Michael Milette
