### ISSUE TITLE
More block level settings, one API key for entire university is impractical

### ISSUE THREAD

**Issue by mronkko** [Limekiller/moodle-block_openai_chat#17]
Would it be possible to have OpenAI API key also as a block level setting. On a large Moodle instance in a university with multiple departments, using one API key for the entire university is impractical. 

I guess that all this would apply to all settings because it would be desirable that the AI had different personas on different courses. But the API key is critical because it is a show stopper for adoption in our university.

**Comment by Limekiller** [comment]
I have this implemented and it will be added in version 1.7. I'm waiting to get more feedback on some other feature requests before releasing it to the directory, but in the meantime, you can try it out by switching to the https://github.com/Limekiller/moodle-block_openai_chat/tree/release-1.7 branch. You will need to enable the "Instance-level settings" option in the main plugin settings.

If you do try it out and find any bugs in the implementation, please open a new issue and I'll try to get to them ASAP.
