### ISSUE TITLE
Validation error while installing in Moodle v3.9.1

### ISSUE THREAD

**Issue by Mylji** [Limekiller/moodle-block_openai_chat#21]
We haven't been able to install the extension due to a version validation error. Our current build is 3.9.1 (20200713), which should be supported by the plugin. Changing the version does not fix the problem.

The error message shown is the following (translated):

Validating openai_chat... Error
      [Error] Required Moodle version [2020061513]
Installation aborted due validation error

**Comment by Mylji** [comment]
Found out or version of Moodle is should be 2020061501, which is not supported, as 2020061513 seems to be required. Sadly, updating the version doesnt seem to be possible for us as of now due to administrative reasons.

**Comment by Limekiller** [comment]
There shouldn't be any reason why the plugin wouldn't work on 3.9.1 -- you can change the version.php file of the plugin to require 20200713 instead of the current value for the time being in order to install the plugin; I will make sure this is fixed in the next release.

**Comment by Mylji** [comment]
Hi Bryce, thanks for answering.

Few days ago I tried what you said: manually changing the version.php for it to require a version compatible with ours. It did installed the plugin, but after trying to implement it into the page, we started getting a syntax error whenever we try to access the Site Administrator page.

Sadly, we still haven't figured out a fix for this. I'll keep you updated in case we do.

**Comment by Limekiller** [comment]
Try removing the trailing comma on line 79 of https://github.com/Limekiller/moodle-block_openai_chat/blob/1d43c71033b856ac9b4ae6d7faef9842174e0a7b/settings.php#L79

This is an issue with PHP versions earlier than 8.0, where PHP isn't behaviorally consistent (see https://wiki.php.net/rfc/trailing_comma_in_parameter_list). I'm looking to change this in the next release as well.

**Comment by Limekiller** [comment]
I've released these fixes on GitHub in a new branch you can find here: https://github.com/Limekiller/moodle-block_openai_chat/tree/release-1.7

I'm waiting to get more feedback on other feature requests before releasing a new version to the directory, but feel free to switch to this branch to fix the issues you're facing.
