### ISSUE TITLE
Support for ChatGPT-4

### ISSUE THREAD

**Issue by michael-milette** [Limekiller/moodle-block_openai_chat#22]
Thanks for sharing this useful plugin.

When do you think that you might be adding support for ChatGPT-4?

Best regards,

Michael

**Comment by Limekiller** [comment]
Hi Michael, GPT-4 is included in [1.7](https://github.com/Limekiller/moodle-block_openai_chat/tree/release-1.7). I'm waiting for feedback on other feature requests before releasing this version to the plugin directory, but you can switch to the release-1.7 branch now to access it right away.

**Comment by michael-milette** [comment]
Thank you @Limekiller !
