### ISSUE TITLE
Automatically set focus after completion response to Ask a Question field

### ISSUE THREAD

**Issue by michael-milette** [Limekiller/moodle-block_openai_chat#23]
Hi,

When I ask a question and OpenAI Chat responds, I need to move my hand to my mouse in order to click the "Ask a Question" field again to ask my next question.

It would be nice if the current focus automatically returned to the Ask a Question field so that the user could just continue typing.

Let me know if you have any questions.

Best regards,

Michael Milette

**Comment by Limekiller** [comment]
Added in 6ad8bc6

**Comment by michael-milette** [comment]
Thank you!
