### ISSUE TITLE
Accessibility issue with screen readers

### ISSUE THREAD

**Issue by michael-milette** [Limekiller/moodle-block_openai_chat#24]
Good day,

Would it be possible to implement this in such a way that screen readers would read the completion response? For someone who is visually impaired, it would be a real pain to always have to click on the response in order to have the screen reader read the response.

Best regards,

Michael Milette

**Comment by Limekiller** [comment]
I've added a `role=log` property to the chat window, allowing screen readers to automatically read updates (tested with NVDA). However, the text labels above each message cause a real issue and aren't read in order -- I recommend using the "disable labels" option of the chat block if this is undesired.

(added in a3919c7)

**Comment by michael-milette** [comment]
Thank you!
