### ISSUE TITLE
Add chat block to moodle classes

### ISSUE THREAD

**Issue by NickCarroll22** [Limekiller/moodle-block_openai_chat#28]
How can I add the pluguin to a moodle course, leave it in the tabs so that it's always available for students to use throughout their stay on the site?

**Comment by Limekiller** [comment]
Hi Nick,

The plugin is a Moodle block, which means it can't do anything that Moodle blocks can't: a block can be added to a context, and appear in the block sidebar on any page within that context, but not outside of it.

That said, the 2.0 release will include support for the Assistants API, which enables conversations to persist between page loads -- so you could add a block to a course, and the same conversation can be carried between any page loads within that course. This doesn't fully match your request, but I wanted you to be aware of the functionality in case it approaches your usecase. The feature is available now on the release-2.0 branch and will come to the plugins repository soon.
