### ISSUE TITLE
add moodle log events

### ISSUE THREAD

**Issue by Manu-REMY** [Limekiller/moodle-block_openai_chat#29]
Hi,

Would it be possible to add an event to moodle log each time a user makes a request in the openAI block?

It would be very useful to know which users are using the block and how often they use it in order to help users who aren't using it and to evaluate if the use of this block helps users to succeed the tasks they are involved in.

It will also bu useful to monitor the number of token for each request : does the students use many token in their requests? Does GPT use many token in his answers? For the moment, it is only possible to monitor the number of tokens used in openAI dashboard but it is not possible to know how many requests have been done to reach this number.

Thanks.

**Comment by Limekiller** [comment]
Added in https://github.com/Limekiller/moodle-block_openai_chat/releases/tag/2.2.0.

**Comment by Manu-REMY** [comment]
Hi,

Great feature! Thanks.
