### ISSUE TITLE
40px width answer

### ISSUE THREAD

**Issue by Manu-REMY** [Limekiller/moodle-block_openai_chat#31]
Hi,

I'm using your block with Moodle 4.3. Since the 1.7.0 update, the answer is presented with quite a single character per column : in fact the width of the answer is set to 40px  :
- div class="openai_message bot" style="width: 40px;" id="yui_3_18_1_1_1699593788478_27"

as the user message is set to 646px :
- div class="openai_message user" style="width: 646px;"><span>...</span></div>

Thanks for this great block!

**Comment by Limekiller** [comment]
Hi @Manu-REMY, thanks for the report. What Moodle version, browser, and browser version are you using?

**Comment by Manu-REMY** [comment]
Hi @Limekiller,
I'm using Moodle 4.3 and safari Version 17.2 (19617.1.11.11.3). You're right : with Firefox 119.0.1, it's just fine.

Thanks

**Comment by Limekiller** [comment]
Thanks again for reporting this -- I will be releasing a 2.0 version before January 4th (when the legacy completion API is deprecated) and a fix for this issue will be included. This fix is available now on the "release-2.0" branch as well.
