### ISSUE TITLE
mobile "openai_message bot" error

### ISSUE THREAD

**Issue by Course-Creativ** [Limekiller/moodle-block_openai_chat#33]
Hello! Only on mobile does the chat response provide the answer in a single column. See attachment

This has been tested on chrome, firefox and safari yielding the same results.

The desktop presents the answers  in a "full" window.

![openai error](https://github.com/Limekiller/moodle-block_openai_chat/assets/119945743/5811544b-118e-446a-b761-7e24c7b7ecfd)

**Comment by Course-Creativ** [comment]
Hello! Does anyone support this app?

**Comment by Course-Creativ** [comment]
No worries. 

We fixed your code. 

I was just frustrated that if a product is offered, even for free, their should be some type of SLA disclosed for issues. 

 

Have a good one!

 

Carl

**Comment by SamMcCullough** [comment]
@Course-Creativ I am experiencing this problem as well. What did you do to fix the problem? Can you share your solution please?

**Comment by Limekiller** [comment]
@SamMcCullough Which version of the plugin are you on? This should be fixed in the latest release.

**Comment by SamMcCullough** [comment]
@Limekiller the site I have running this block is on Moodle 3.9 currently. It uses version 1.7.0. I am planning to upgrade it to 4.1 soon, which would allow me to update to the 2.0.0 version.
