### ISSUE TITLE
Support other LLM Modle

### ISSUE THREAD

**Issue by WilliamMrxia** [Limekiller/moodle-block_openai_chat#35]
Now the  block plugin supports openai_chat, how to change it to support other LLM modle.

**Comment by fishfree** [comment]
Good idea! I think add configurations for API HTTP endpoint URL and authentication bearer token are enought per instance are enought. Other stuff can be done with some OpenAI compatible API bridges.

**Comment by Limekiller** [comment]
This plugin relies entirely on the features provided by the OpenAI API, and generalizing the code to other APIs is non-trivial and not planned at this time.
