### ISSUE TITLE
All settings are always loaded

### ISSUE THREAD

**Issue by ewallah** [Limekiller/moodle-block_openai_chat#38]
Settings should only be loaded when necessary. Normally this is done by adding `if ($hassiteconfig) {` and `if ($ADMIN->fulltree) {` in the [settings file](https://deploy-preview-852--moodledevdocs.netlify.app/docs/apis/subsystems/admin#settings-file-example).

Detected when running Behat tests:
`Exception: Javascript code and/or AJAX requests are not ready after 10 seconds. There is a Javascript error or the code is extremely slow (block_openai_chat/settings).`

**Comment by Limekiller** [comment]
Thanks for the report. I think this should be fixed by https://github.com/Limekiller/moodle-block_openai_chat/commit/7e6d984046b06727f49665b5100692f0eeefbb35
