### ISSUE TITLE
hard coded lang string

### ISSUE THREAD

**Issue by danmarsden** [Limekiller/moodle-block_openai_chat#4]
https://github.com/Limekiller/moodle-block_openai_chat/blob/main/block_openai_chat.php#L85

please note - all user-facing strings must be included in the lang file so they can be translated and presented in the users selected language.

**Comment by Limekiller** [comment]
Fixed in https://github.com/Limekiller/moodle-block_openai_chat/commit/9066841fc7012d5bcd17f3dfd93549813eb5e230
