### ISSUE TITLE
Moodle AI Chat Interface Activity in development...

### ISSUE THREAD

**Issue by taymossimc** [Limekiller/moodle-block_openai_chat#41]
Bryce, I've tied emailing you a couple of times. Please check your spam folders. 

My team and I are pretty well advanced in creating a similar Moodle Plugin, but instead of a block it's based on an "Activity" format, with the intention that teachers would use it as a kind of virtual TA. Something like this is already being done in some institutions, just without the Moodle integration.  Our plugin is about 5% based on your code, the rest is new. 

Anyway, I'd like to open a channel of collaboration between the two projects, as I think they are probably distinct but related projects. Especially since once we release the plugin (maybe in the next week or two) we are going to shift focus onto implementing a "RAG for Moodle" based on on the Pruju project. Then we are going to add functionality to connect our AI Chat activity to that RAG.

The goal of our project is to make it easy for a Instructor or Instructional Designer to designate material from a course to be indexed by the RAG and then to send that off to the RAG we are building for indexing. This plugin woud also monitor that designated material for updates and update the RAG on some scheduled basis. 

Anyway, I think it would be great if could collaborate or at least be more aware of each other's projects. Probably email would be better for that, so please check your me@... address. Thanks!

**Comment by Limekiller** [comment]
Thanks Tay :) I've responded to your email
