### ISSUE TITLE
Enable indicating also PDFs as "Source of Truth"

### ISSUE THREAD

**Issue by sfkeller** [Limekiller/moodle-block_openai_chat#43]
This is a feature request. 

ChatGPT and Large Language Models (LLMs) are limited to the information they were trained on. As a result, they are often outdated or hallucinate. This is where the Source of Truth comes in, using the Retrieval Augmented Generation (RAG) technique. The RAG technique combines the user's query with contextual information before asking the LLM to generate an answer. It can also list the sources (i.e. the PDF name and slide number) used to generate the answers, allowing the student to verify the answer. 

Currently, in the moodle-block_openai_chat plugin the "Source of Truth" with its Q&A is available as a form of contextual information. By using lecture notes and lecture material (as a PDF), the chatbot can not only provide better answers, but also the sources. Teachers don't need to formulate questions and answers in advance. 

Current state: Input to moodle-block_openai_chat as text containing Q&A, entered by teachers or administrators.

Expected state: Add thi fnctionality as a separate section of moodle-block_openai_chat below "Q&A" to upload PDFs - or link to already uploaded PDF Moodle file resources. 

Output behavour: Same as in current chat, but with an indication of the sources (see page 12 in PDF "blabla"). 

See also....: I'm not aware of such a plugin in Moodle. For similar websites (which have limited free plans), see e.g. [AskYourPDF and alternatives](https://askyourpdf.com/blog/top-5-chatpdf-alternatives).

**Comment by OkorrDev** [comment]
Supported, and in addition to PDFs, teachers to also be able to add websites as data sources. Might be a legal hurdle though.

**Comment by Limekiller** [comment]
Hey sfkeller, I recommend using the Assistants API for this. This API allows you to create Assistants in your OpenAI account that you can then use in the Moodle plugin, and OpenAI includes a way to upload documents for these Assistants to pull from when they generate their responses.
