### ISSUE TITLE
Hi Limekiller,

### ISSUE THREAD

**Issue by kirupalaksh** [Limekiller/moodle-block_openai_chat#44]
Hi Limekiller,
I am developing an activity plugin for chat bot on OpenAI integrating api from python. Completed 70% of development now gradebook implementation is in progress.

Your Plugin solves our needs super. As this is block plugin i am not able to grade the history or chat anyway. 
Are you planning to add Claude as next option ?  it will be useful. Thanks

_Originally posted by @kirupalaksh in https://github.com/Limekiller/moodle-block_openai_chat/issues/41#issuecomment-1942217709_

**Comment by taymossimc** [comment]
@kirupalaksh are you going to release your activity pugin as Open Source? Note we just released ours today https://github.com/caiocarvalhofre/mod_maici
