### ISSUE TITLE
How can I use a free Huggin face API instead of an OpenIA api?

### ISSUE THREAD

**Issue by wanders0n** [Limekiller/moodle-block_openai_chat#51]
I've been following the project for a few months and I think it's a great idea, but instead of using a GPT chat API I'm interested in using a free rugby 3 API. How do I proceed in this case?

**Comment by Limekiller** [comment]
This plugin relies entirely on the features provided by the OpenAI API, and generalizing the code to other APIs is non-trivial and not planned at this time.
