### ISSUE TITLE
The plugin is not working

### ISSUE THREAD

**Issue by JuaniV2002** [Limekiller/moodle-block_openai_chat#53]
The plugin was working flawlessly up until 3 days ago. Whenever I prompt the assistant, it wouldn't reply, instead, an error will show up in the prompt bar saying: "An error ocurred! Please try again later".
I tried generating a different API key (which I got from OpenAI's official website) but still no success. Fix it ASAP please. 
Thank you in advance!

**Comment by Limekiller** [comment]
Hi @JuaniV2002, that's an issue with your OpenAI account. This message is telling you that you've exceeded your limit of requests to OpenAI. Check your billing settings and make sure you have enough funds; otherwise, reach out to OpenAI support.
