### ISSUE TITLE
styles.css not specific enough

### ISSUE THREAD

**Issue by danmarsden** [Limekiller/moodle-block_openai_chat#6]
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

in particular - your keyframe classes:
https://github.com/Limekiller/moodle-block_openai_chat/blob/main/styles.css#L57-L70

Moodle collects the styles.css files across all plugins and bundles them into a single css file sent to the users browser - this helps with caching and performance, but it means you must be careful not to write css that could clash with other core classes.

Moodle also helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by Limekiller** [comment]
Fixed in https://github.com/Limekiller/moodle-block_openai_chat/commit/59525906396d1b8733cf963b705b639b3a8bde08
