### ISSUE TITLE
please use core curl class instead of calling curl_init

### ISSUE THREAD

**Issue by danmarsden** [Limekiller/moodle-block_openai_chat#7]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

Many organisations put their moodle site behind a web proxy and the internal curl wrapper takes care of this for you.

**Comment by Limekiller** [comment]
Fixed in https://github.com/Limekiller/moodle-block_openai_chat/commit/472fd77c239b5c96a0ba834f450cc5b9f408d39f
