### ISSUE TITLE
never trust user input.

### ISSUE THREAD

**Issue by danmarsden** [Limekiller/moodle-block_openai_chat#8]
see: https://docs.moodle.org/dev/Security#Don.27t_trust_any_input_from_users

this code here takes content submitted from the user, but does not perform any cleaning of the data before it's used.
https://github.com/Limekiller/moodle-block_openai_chat/blob/main/api/completion.php#L28

Moodle provides a number of APIS to help with this - in your case it might be easiest to use the clean_param() function using the appropriate PARAM_XXXX for each datatype that you pull from the POST.

**Comment by Limekiller** [comment]
Fixed in https://github.com/Limekiller/moodle-block_openai_chat/commit/fe8410fc806a250c5b7b2a50581349434324a66f
